# Generated by Django 5.1.1 on 2024-09-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
