# Generated by Django 5.1.1 on 2024-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubereats',
            name='Latitude',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ubereats',
            name='Longitude',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ubereats',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ubereats',
            name='rating',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ubereats',
            name='shop_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='ubereats',
            name='shop_url',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='MealzoZoho',
            fields=[
                ('Account_Number', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('View_in_Mealzo', models.CharField(blank=True, max_length=255, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('Rating', models.CharField(blank=True, max_length=255, null=True)),
                ('Account_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer_Data_Base', models.CharField(blank=True, max_length=255, null=True)),
                ('GB_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Installation_date', models.CharField(blank=True, max_length=255, null=True)),
                ('IOS_App_Link', models.CharField(blank=True, max_length=255, null=True)),
                ('Android_App_Link', models.CharField(blank=True, max_length=255, null=True)),
                ('Landing_Page', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Caller', models.CharField(blank=True, max_length=255, null=True)),
                ('Delivery_Bag', models.CharField(blank=True, max_length=255, null=True)),
                ('Package', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('APOS', models.CharField(blank=True, max_length=255, null=True)),
                ('Booking', models.CharField(blank=True, max_length=255, null=True)),
                ('Mealzo_Card_Machine', models.CharField(blank=True, max_length=255, null=True)),
                ('TV', models.CharField(blank=True, max_length=255, null=True)),
                ('Self_Ordering_Kiosk', models.CharField(blank=True, max_length=255, null=True)),
                ('Social_Responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('Website', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Mealzo_Data',
                'indexes': [models.Index(fields=['Account_Number', 'Account_Name', 'Rating', 'Longitude', 'Latitude', 'Phone'], name='Mealzo_Data_Account_bc5bea_idx')],
            },
        ),
    ]
