# Generated by Django 5.1.1 on 2024-10-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_ubereats_latitude_alter_ubereats_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='justeat',
            table='Justeat_v2',
        ),
    ]
