# Generated by Django 5.1.1 on 2024-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, null=True, unique=True)),
                ('account_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('duplicated', models.CharField(max_length=255, null=True)),
                ('sunday', models.TextField(null=True)),
                ('monday', models.TextField(null=True)),
                ('tuesday', models.TextField(null=True)),
                ('wednesday', models.TextField(null=True)),
                ('thursday', models.TextField(null=True)),
                ('friday', models.TextField(null=True)),
                ('saturday', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('account_id', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=7, null=True)),
            ],
            options={
                'db_table': 'business_information',
                'indexes': [models.Index(fields=['account_id'], name='business_in_account_41b02c_idx')],
            },
        ),
    ]
